// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/rescript-jest/src/jest.bs.js");

require("@testing-library/jest-dom")
;

function toBeInTheDocument(e) {
  e.toBeInTheDocument();
  return Jest.pass;
}

function toBeVisible(e) {
  e.toBeVisible();
  return Jest.pass;
}

function toHaveAttribute(name, value, e) {
  if (value !== undefined) {
    e.toHaveAttribute(name, value);
  } else {
    e.toHaveAttribute(name);
  }
  return Jest.pass;
}

function toHaveTextContent(text, e) {
  e.toHaveTextContent(text.VAL);
  return Jest.pass;
}

exports.toBeInTheDocument = toBeInTheDocument;
exports.toBeVisible = toBeVisible;
exports.toHaveAttribute = toHaveAttribute;
exports.toHaveTextContent = toHaveTextContent;
/*  Not a pure module */
