// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/rescript-jest/src/jest.bs.js");
var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var TestUtils = require("./TestUtils.bs.js");
var ReactTestingLibrary = require("rescript-react-testing-library/src/ReactTestingLibrary.bs.js");
var Listboxkit__ListboxComponent = require("../src/Listboxkit__ListboxComponent.bs.js");

var activeClassName = "highlighted";

function component(multiSelectOpt, param) {
  var multiSelect = multiSelectOpt !== undefined ? multiSelectOpt : true;
  return React.createElement("div", undefined, React.createElement(Listboxkit__ListboxComponent.make, {
                  activeClassName: activeClassName,
                  multiSelect: multiSelect,
                  options: [
                    "Red",
                    "Green",
                    "Blue"
                  ]
                }), React.createElement("div", {
                  tabIndex: 0
                }, "Focus out"));
}

Jest.test("render listbox container", (function (param) {
        return TestUtils.toBeInTheDocument(expect(Curry._1(TestUtils.getListbox(undefined), ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, component(undefined, undefined)))));
      }));

Jest.test("renders the options: Red, Green and Blue", (function (param) {
        var component$1 = ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, component(undefined, undefined));
        TestUtils.assertAndContinue(TestUtils.toBeInTheDocument(expect(TestUtils.getOption(component$1, "Red"))));
        TestUtils.assertAndContinue(TestUtils.toBeInTheDocument(expect(TestUtils.getOption(component$1, "Green"))));
        return TestUtils.toBeInTheDocument(expect(TestUtils.getOption(component$1, "Blue")));
      }));

Jest.test("highlights last option when pressing END", (function (param) {
        var component$1 = ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, component(undefined, undefined));
        TestUtils.FireEvent.pressEnd(TestUtils.getOption(component$1, "Red"));
        return TestUtils.toBeHighlighted(expect(TestUtils.getOption(component$1, "Blue")));
      }));

Jest.test("highlights first option when pressing HOME", (function (param) {
        var component$1 = ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, component(undefined, undefined));
        TestUtils.FireEvent.pressHome(TestUtils.getOption(component$1, "Blue"));
        return TestUtils.toBeHighlighted(expect(TestUtils.getOption(component$1, "Red")));
      }));

Jest.test("sets option aria-selected to true when clicked", (function (param) {
        var component$1 = ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, component(undefined, undefined));
        TestUtils.FireEvent.click(component$1);
        TestUtils.FireEvent.click(TestUtils.getOption(component$1, "Red"));
        return TestUtils.toHaveAttribute("aria-selected", "true", expect(TestUtils.getOption(component$1, "Red")));
      }));

Jest.test("highlights next option when pressing DOWN ", (function (param) {
        var component$1 = ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, component(undefined, undefined));
        var listbox = Curry._1(TestUtils.getListbox(undefined), component$1);
        TestUtils.FireEvent.pressDown(listbox);
        TestUtils.assertAndContinue(TestUtils.toBeHighlighted(expect(TestUtils.getOption(component$1, "Green"))));
        TestUtils.FireEvent.pressDown(listbox);
        TestUtils.assertAndContinue(TestUtils.toBeHighlighted(expect(TestUtils.getOption(component$1, "Blue"))));
        TestUtils.FireEvent.pressDown(listbox);
        return TestUtils.toBeHighlighted(expect(TestUtils.getOption(component$1, "Red")));
      }));

Jest.test("highlights previous option when pressing UP ", (function (param) {
        var component$1 = ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, component(undefined, undefined));
        var listbox = Curry._1(TestUtils.getListbox(undefined), component$1);
        TestUtils.FireEvent.pressUp(listbox);
        TestUtils.assertAndContinue(TestUtils.toBeHighlighted(expect(TestUtils.getOption(component$1, "Blue"))));
        TestUtils.FireEvent.pressUp(listbox);
        TestUtils.assertAndContinue(TestUtils.toBeHighlighted(expect(TestUtils.getOption(component$1, "Green"))));
        TestUtils.FireEvent.pressUp(listbox);
        TestUtils.assertAndContinue(TestUtils.toBeHighlighted(expect(TestUtils.getOption(component$1, "Red"))));
        TestUtils.FireEvent.pressUp(listbox);
        return TestUtils.toBeHighlighted(expect(TestUtils.getOption(component$1, "Blue")));
      }));

Jest.test("selects and deselects option when pressing SPACE/ENTER", (function (param) {
        var component$1 = ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, component(false, undefined));
        TestUtils.FireEvent.click(TestUtils.getOption(component$1, "Red"));
        TestUtils.assertAndContinue(TestUtils.toHaveAttribute("aria-selected", "true", expect(TestUtils.getOption(component$1, "Red"))));
        TestUtils.FireEvent.pressEnter(Curry._1(TestUtils.getListbox(undefined), component$1));
        TestUtils.assertAndContinue(TestUtils.toHaveAttribute("aria-selected", "false", expect(TestUtils.getOption(component$1, "Red"))));
        TestUtils.FireEvent.pressSpace(Curry._1(TestUtils.getListbox(undefined), component$1));
        return TestUtils.toHaveAttribute("aria-selected", "true", expect(TestUtils.getOption(component$1, "Red")));
      }));

Jest.test("highlights first when focused and no option selected", (function (param) {
        var component$1 = ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, component(undefined, undefined));
        var listbox = Curry._1(TestUtils.getListbox(undefined), component$1);
        TestUtils.FireEvent.click(listbox);
        return TestUtils.toBeHighlighted(expect(TestUtils.getOption(component$1, "Red")));
      }));

Jest.Only.test("highlights selected index when focus and option is selected", (function (param) {
        var component$1 = ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, component(undefined, undefined));
        TestUtils.FireEvent.click(TestUtils.getOption(component$1, "Green"));
        TestUtils.assertAndContinue(TestUtils.toBeHighlighted(expect(TestUtils.getOption(component$1, "Green"))));
        TestUtils.FireEvent.pressDown(Curry._1(TestUtils.getListbox(undefined), component$1));
        TestUtils.assertAndContinue(TestUtils.toBeHighlighted(expect(TestUtils.getOption(component$1, "Blue"))));
        TestUtils.FireEvent.tab(undefined);
        TestUtils.FireEvent.click(Curry._1(TestUtils.getListbox(undefined), component$1));
        return TestUtils.toBeHighlighted(expect(TestUtils.getOption(component$1, "Green")));
      }));

Jest.test("resets highlighted option when focus out", (function (param) {
        var component$1 = ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, component(undefined, undefined));
        var listbox = Curry._1(TestUtils.getListbox(undefined), component$1);
        TestUtils.FireEvent.pressDown(listbox);
        TestUtils.assertAndContinue(TestUtils.toBeInTheDocument(expect(TestUtils.getOption(listbox, "* Green"))));
        TestUtils.FireEvent.tab(undefined);
        TestUtils.FireEvent.focus(listbox);
        return TestUtils.toBeInTheDocument(expect(TestUtils.getOption(listbox, "Green")));
      }));

Jest.test("focus out when pressing Tab", (function (param) {
        var component$1 = ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, component(undefined, undefined));
        TestUtils.FireEvent.tab(undefined);
        TestUtils.assertAndContinue(TestUtils.toBeInTheDocument(expect(TestUtils.getOption(component$1, "* Red"))));
        TestUtils.FireEvent.tab(undefined);
        TestUtils.assertAndContinue(TestUtils.toBeInTheDocument(expect(TestUtils.getOption(component$1, "Red"))));
        TestUtils.assertAndContinue(TestUtils.toBeInTheDocument(expect(TestUtils.getOption(component$1, "Green"))));
        return TestUtils.toBeInTheDocument(expect(TestUtils.getOption(component$1, "Blue")));
      }));

Jest.test("selects multiple when multiSelect is true", (function (param) {
        var component$1 = ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, component(true, undefined));
        TestUtils.FireEvent.tab(undefined);
        TestUtils.FireEvent.pressEnter(Curry._1(TestUtils.getListbox(undefined), component$1));
        TestUtils.assertAndContinue(TestUtils.toHaveAttribute("aria-selected", "true", expect(TestUtils.getOption(component$1, "* Red"))));
        TestUtils.FireEvent.pressDown(Curry._1(TestUtils.getListbox(undefined), component$1));
        TestUtils.FireEvent.pressEnter(Curry._1(TestUtils.getListbox(undefined), component$1));
        TestUtils.FireEvent.pressDown(Curry._1(TestUtils.getListbox(undefined), component$1));
        TestUtils.FireEvent.pressEnter(Curry._1(TestUtils.getListbox(undefined), component$1));
        return TestUtils.toHaveAttribute("aria-selected", "true", expect(TestUtils.getOption(component$1, "Red")));
      }));

Jest.test("selects next when pressing arrow down and shift", (function (param) {
        var component$1 = ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, component(true, undefined));
        TestUtils.FireEvent.tab(undefined);
        TestUtils.FireEvent.pressDownShift(Curry._1(TestUtils.getListbox(undefined), component$1));
        return TestUtils.toHaveAttribute("aria-selected", "true", expect(TestUtils.getOption(component$1, "* Green")));
      }));

Jest.test("selects previous when pressing arrow up and shift", (function (param) {
        var component$1 = ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, component(true, undefined));
        TestUtils.FireEvent.tab(undefined);
        TestUtils.FireEvent.pressUpShift(Curry._1(TestUtils.getListbox(undefined), component$1));
        return TestUtils.toHaveAttribute("aria-selected", "true", expect(TestUtils.getOption(component$1, "* Blue")));
      }));

var FireEvent = TestUtils.FireEvent;

var getListbox = TestUtils.getListbox;

var getButton = TestUtils.getButton;

var getOption = TestUtils.getOption;

var useFakeTimers = TestUtils.useFakeTimers;

var setSystemTime = TestUtils.setSystemTime;

var toBeInTheDocument = TestUtils.toBeInTheDocument;

var toBeVisible = TestUtils.toBeVisible;

var toHaveAttribute = TestUtils.toHaveAttribute;

var assertAndContinue = TestUtils.assertAndContinue;

var toEqual = TestUtils.toEqual;

var toHaveTextContent = TestUtils.toHaveTextContent;

var toBeHighlighted = TestUtils.toBeHighlighted;

var toBeSelected = TestUtils.toBeSelected;

exports.FireEvent = FireEvent;
exports.getListbox = getListbox;
exports.getButton = getButton;
exports.getOption = getOption;
exports.useFakeTimers = useFakeTimers;
exports.setSystemTime = setSystemTime;
exports.toBeInTheDocument = toBeInTheDocument;
exports.toBeVisible = toBeVisible;
exports.toHaveAttribute = toHaveAttribute;
exports.assertAndContinue = assertAndContinue;
exports.toEqual = toEqual;
exports.toHaveTextContent = toHaveTextContent;
exports.toBeHighlighted = toBeHighlighted;
exports.toBeSelected = toBeSelected;
exports.activeClassName = activeClassName;
exports.component = component;
/*  Not a pure module */
