// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/rescript-jest/src/jest.bs.js");
var Curry = require("rescript/lib/js/curry.js");
var JestDom = require("./JestDom.bs.js");
var ReactTestingLibrary = require("rescript-react-testing-library/src/ReactTestingLibrary.bs.js");
var DomTestingLibrary__UserEvent = require("rescript-dom-testing-library/src/DomTestingLibrary__UserEvent.bs.js");

var down = "{arrowdown}";

var downShift = "{shift}{arrowDown}";

var end = "{end}";

var enter = "{enter}";

var esc = "{esc}";

var home = "{home}";

var space = "{space}";

var tab = "{Tab}";

var up = "{arrowUp}";

var upShift = "{shift}{arrowUp}";

var Keyboard = {
  down: down,
  downShift: downShift,
  end: end,
  enter: enter,
  esc: esc,
  home: home,
  space: space,
  tab: tab,
  up: up,
  upShift: upShift
};

function pressKeyboardDown(param) {
  DomTestingLibrary__UserEvent.keyboard(undefined, down);
}

function pressKeyboardUp(param) {
  DomTestingLibrary__UserEvent.keyboard(undefined, up);
}

function pressKeyboardEnter(param) {
  DomTestingLibrary__UserEvent.keyboard(undefined, enter);
}

function pressKeyboardSpace(param) {
  DomTestingLibrary__UserEvent.keyboard(undefined, space);
}

function pressDown(e) {
  DomTestingLibrary__UserEvent.type_(undefined, e, down);
}

function pressDownShift(e) {
  DomTestingLibrary__UserEvent.type_(undefined, e, downShift);
}

function pressEnd(e) {
  DomTestingLibrary__UserEvent.type_(undefined, e, end);
}

function pressEnter(e) {
  DomTestingLibrary__UserEvent.type_(undefined, e, enter);
}

function pressEsc(e) {
  DomTestingLibrary__UserEvent.type_(undefined, e, esc);
}

function pressHome(e) {
  DomTestingLibrary__UserEvent.type_(undefined, e, home);
}

function pressSpace(e) {
  DomTestingLibrary__UserEvent.type_(undefined, e, space);
}

function pressTab(e) {
  DomTestingLibrary__UserEvent.type_(undefined, e, tab);
}

function pressUp(e) {
  DomTestingLibrary__UserEvent.type_(undefined, e, up);
}

function pressUpShift(e) {
  DomTestingLibrary__UserEvent.type_(undefined, e, upShift);
}

function click(e) {
  DomTestingLibrary__UserEvent.click(undefined, undefined, e);
}

function blur(param) {
  
}

function focus(param) {
  
}

function tab$1(param) {
  DomTestingLibrary__UserEvent.tab(undefined, undefined);
}

var FireEvent = {
  Keyboard: Keyboard,
  pressKeyboardDown: pressKeyboardDown,
  pressKeyboardUp: pressKeyboardUp,
  pressKeyboardEnter: pressKeyboardEnter,
  pressKeyboardSpace: pressKeyboardSpace,
  pressDown: pressDown,
  pressDownShift: pressDownShift,
  pressEnd: pressEnd,
  pressEnter: pressEnter,
  pressEsc: pressEsc,
  pressHome: pressHome,
  pressSpace: pressSpace,
  pressTab: pressTab,
  pressUp: pressUp,
  pressUpShift: pressUpShift,
  click: click,
  blur: blur,
  focus: focus,
  tab: tab$1
};

function getListbox(param) {
  return Curry._2(ReactTestingLibrary.getByRole, param, {
              NAME: "Str",
              VAL: "listbox"
            });
}

function getButton(param) {
  return Curry._2(ReactTestingLibrary.getByRole, param, {
              NAME: "Str",
              VAL: "button"
            });
}

function getOption(e, name) {
  return ReactTestingLibrary.getByRole(ReactTestingLibrary.makeByRoleOptions(undefined, undefined, name, undefined), {
              NAME: "Str",
              VAL: "option"
            }, e);
}

function assertAndContinue(param) {
  
}

function toEqual(a, b) {
  return Jest.Expect.toEqual(a, b);
}

function toHaveTextContent(a, b) {
  return JestDom.toHaveTextContent(b, a);
}

function toBeHighlighted(expect) {
  return JestDom.toHaveAttribute("class", "highlighted", expect);
}

function toBeSelected(expect) {
  return JestDom.toHaveAttribute("aria-selected", "true", expect);
}

var useFakeTimers = Jest.Jest.useFakeTimers;

var setSystemTime = Jest.Jest.setSystemTime;

var toBeInTheDocument = JestDom.toBeInTheDocument;

var toBeVisible = JestDom.toBeVisible;

var toHaveAttribute = JestDom.toHaveAttribute;

exports.FireEvent = FireEvent;
exports.getListbox = getListbox;
exports.getButton = getButton;
exports.getOption = getOption;
exports.useFakeTimers = useFakeTimers;
exports.setSystemTime = setSystemTime;
exports.toBeInTheDocument = toBeInTheDocument;
exports.toBeVisible = toBeVisible;
exports.toHaveAttribute = toHaveAttribute;
exports.assertAndContinue = assertAndContinue;
exports.toEqual = toEqual;
exports.toHaveTextContent = toHaveTextContent;
exports.toBeHighlighted = toBeHighlighted;
exports.toBeSelected = toBeSelected;
/* Jest Not a pure module */
